# Generated by Django 5.2 on 2025-04-15 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='fire_photos/')),
                ('location', models.CharField(max_length=255)),
                ('time', models.DateTimeField()),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
