# Generated by Django 5.2 on 2025-04-24 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fires', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fire',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fire',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
