# Generated by Django 5.2.5 on 2025-09-04 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fires', '0002_fire_latitude_fire_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='fire',
            name='conf',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
