# Generated by Django 5.2.5 on 2026-02-13 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fires', '0005_add_session_audit_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('moderator', 'Moderator'), ('member', 'Member')], default='member', max_length=10),
        ),
    ]
