# Generated by Django 5.2.5 on 2026-02-13 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fires', '0006_add_moderator_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionauditlog',
            name='role_granted',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sessionauditlog',
            name='action',
            field=models.CharField(choices=[('approved', 'Approved'), ('denied', 'Denied'), ('blocked', 'Blocked'), ('unblocked', 'Unblocked'), ('removed', 'Removed'), ('role_changed', 'Role changed')], max_length=20),
        ),
    ]
